version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 1.17.3

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '127.0.0.1'


    working_directory: ~/kokoita

    steps:
      - checkout

      - run:
          name: Bundler install
          command: |
            gem update --system
            gem install bundler -v 1.17.3


      - restore_cache:
          keys:
            - kokoita-bundle-v4-{{ checksum "Gemfile.lock" }}
            - kokoita-bundle-v4-
      
      - run:
          name: default mysql client install
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
      
      - run:
          name: bundle Install
          command: bundle check -path vendor/bundle || bundle install --deployment

      - save_cache:
          key: kokoita-bundle-v4-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: wait for db
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      
      - run: 
          name: 
          command: |
            bundle exec rake db:create
            bundle exec rails db:schema:load

      - run:
          name: run rspec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - run:
          name: run rubocop
          command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses
      
      - add_ssh_keys:
          fingerprints:
            - "d7:51:34:bc:a3:9d:de:b1:5a:3f:27:69:0c:39:19:5f"