version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          RAILS_ENV: test

      - image: circleci/mysql:5.7.29
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: kokoita_test


    working_directory: ~/kokoita

    steps:
      - checkout

      - run:
          name: Bundler install
          command: |
            gem update --system
            gem install bundler -v 1.17.3


      - restore_cache:
          keys:
            - kokoita-bundle-v1-{{ checksum "Gemfile.lock" }}
            - kokoita-bundle-v1-
      
      - run:
          name: default mysql client install
          command: |
            sudo qpt update
            sudo qpt-get install default-mysql-client
      
      - run:
          name: bundle Install
          command: bundle check -path vendor/bundle || bundle install --deployment

      - save_cache:
          key: kokoita-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: DBの待機
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      
      - run: bundle exec rails db:scheme:load

      - run:
          name: Rspecの実行
          command: |
            bundle exec rspec --profile 10 \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format progress \
            $(circleci tests glob "spec/**/*/_spec.rb" | circleci tests split --split-by=timings)
      
      - store_test_results:
          path: test_results
